### ISSUE TITLE
Inference Notebook Custom Rules

### ISSUE THREAD

**Issue by dogancancelikk** [SANSA-Stack/SANSA-Notebooks#12]
Hi,

Is there any way to use custom .rules file in inference notebook?

Thank you.

**Comment by patrickwestphal** [comment]
Hi Doğancan,

sorry for the late reply. No, unfortunately there is no way to use custom .rules file right now. Currently this notebook just uses the fixed profiles (RDFS, OWL Horst).

Kind regards,
Patrick
