### ISSUE TITLE
zeppelin and scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.

### ISSUE THREAD

**Issue by antonkulaga** [SANSA-Stack/SANSA-Notebooks#16]
Whenever I try to use any sansa library (of either 0.4.0 or 0.5.0 versions) in zeppelin (Spark 2.3.2) like
```
%spark.dep

z.load("net.sansa-stack:sansa-rdf-spark_2.11:0.4.0")
```
and then do regular import
```
import org.apache.spark._
import org.apache.spark.sql.types._
import org.apache.spark.storage.StorageLevel
import org.apache.spark.sql._
import org.apache.spark.sql.functions._
```
I get:
```
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
```

**Comment by GezimSejdiu** [comment]
Hi all,

I'm not able to debug this issue my self, but somehow I feel that there could be two reason causing this error: 
1. In case you @antonkulaga are using your own instance of Apache Zeppelin and not SANSA-Notebooks, could you please double check which Scala version you are using? SANSA uses `2.11.x` and this may be the cause of the error and also check this a reference: https://issues.apache.org/jira/browse/ZEPPELIN-1511 (it may be related).
2. If anyone of you (maybe you @ChethanUK or @asotona ) are using Java 9, please, could you use Java 8 and see if this solves the issue. 

But in any case, if anyone of you found a workaround, would be great to share it here so all of us know how to fix when this happens again.

Best regards,

**Comment by GezimSejdiu** [comment]
Hi all,
I will close this issue for now. In any case, if the issue still persists, please feel free to reopen and we can discuss and try to find a solution.

Best regards,
