### ISSUE TITLE
Multiple errors in RDF notebook

### ISSUE THREAD

**Issue by nleguillarme** [SANSA-Stack/SANSA-Notebooks#17]
Hi.

When running the RDF notebook in Zeppelin, I run into a number of errors :

- **In PageRank of resources example :** error: value asGraph is not a member of org.apache.spark.rdd.RDD[org.apache.jena.graph.Triple]
- **In Triple Ops example :** java.lang.NoClassDefFoundError: org/apache/http/client/cache/HttpCacheStorage
- **In Triple reader example :** Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.jena.riot.system.RiotLib

Thank you for your help !

**Comment by arunkollan** [comment]
Hi There, I tried the example PageRank using ScalaIDE and I get the same error 

value asGraph is not a member of org.apache.spark.rdd.RDD[org.apache.jena.graph.Triple]

Could you please help me resolve this issue. Thank you

**Comment by arunkollan** [comment]
Ahh.. The issue was I was  importing net.sansa_stack.rdf.spark.model.graph._  rather than  net.sansa_stack.rdf.spark.model._

**Comment by GezimSejdiu** [comment]
Hi @nleguillarme and @arunkollan , we thank you for the issue. 
We fixed the issue of `java.lang.NoClassDefFoundError: Could not initialize class org.apache.jena.riot.system.RiotLib` here: https://github.com/SANSA-Stack/SANSA-Examples/pull/35 and the solution for the `graph` package were to remove it from the model as we put all data structured into one model (rdd, dataframe, dataset, graph) by importing `net.sansa_stack.rdf.spark.model._` only.

Please, give it a try and let us know if you need more help.

Once more, many thanks for using SANSA and looking forward to hearing from you.

Best regards,
