### ISSUE TITLE
SANSA NOTEBOOK USING DOCKER TOOLBOX THROWS ERROR

### ISSUE THREAD

**Issue by niraj7488** [SANSA-Stack/SANSA-Notebooks#19]
I am trying to use SANSA Notebook using Docker Toolbox. I am not able to run **MAKE** command. It throws error "**bash: make: command not found**". Please help.

I am new to this area. I can not install Docker as I do not have windows 10 pro system. I only have window 10 home so I installed docker toolbox for this. 

Kindly let me know if more information is needed. 
![SANSA-Notebook-Error](https://user-images.githubusercontent.com/63467231/79007893-d4393680-7b79-11ea-83ca-3b59cd506f2f.jpg)

**Comment by carstendraschner** [comment]
Hello @niraj7488 ,

Thank you for you interest into the SANSA notebooks stack. Unfortunately a support of Windows 10 Home Docker installation is beyond our support scope. A short first research led to this docker webpage: https://docs.docker.com/docker-for-windows/install-windows-home/ . We cannot check whether this helps with your problem. We wish you all the best to solve this problem. Feel free to share if you fond a solution so others struggling with same problem could benefit from your experience. 

All the best 
Carsten
SANSA Team
